<?php

/**
 * @file
 * Contains dadi.module.
 */

use Drupal\commerce_product\Entity\ProductType;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\commerce_product\Entity\ProductVariationType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\image\Entity\ImageStyle;


/**
 * Implements hook_help().
 */
function dadi_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the dadi module.
    case 'help.page.dadi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dadi custom module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function dadi_form_alter(&$form, FormStateInterface $form_state, $form_id)
{

  $forms_for_validation = [
    "commerce_product_default_edit_form",
    "commerce_product_default_add_form",
    "commerce_product_inse_add_form",
    "commerce_product_inse_edit_form",
    "commerce_product_vzutta_add_form",
    "commerce_product_vzutta_edit_form",
  ];
  if (in_array($form_id, $forms_for_validation)) {
    $form['#validate'][] = 'dadi_on_product_save_validation';
  }

  switch ($form_id) {
    case 'comment_comments_to_products_form':
      $user = \Drupal::currentUser();
      if ($user->id() && $email = $user->getEmail()) {
        $form['field_e_mail']['widget'][0]['value']['#default_value'] = $email;
      }
      $form['#attached']['library'][] = 'core/drupal.dialog.ajax';
      $form['actions']['submit']['#attributes'] = ['class' => ['use-ajax',],];
      $form['actions']['submit']['#ajax'] = [
        'callback' => 'comment_ajax_callback',
        'wrapper' => 'comment-form',
      ];
      break;
    case strpos($form_id, 'commerce_order_item_add_to_cart_form_commerce_product_'):
      if (!empty($form['purchased_entity']['widget'][0]['attributes']['attribute_rozmir'])) {
        $suffix = _get_size_info_content('default');
        $form['purchased_entity']['widget'][0]['attributes']['attribute_rozmir']['#suffix'] = $suffix;
      }
      elseif (!empty($form['purchased_entity']['widget'][0]['attributes']['attribute_size'])) {
        $suffix = _get_size_info_content('vzutta');
        $form['purchased_entity']['widget'][0]['attributes']['attribute_size']['#suffix'] = $suffix;
      }
      break;
  }
}

function _get_size_info_content($type){
  global $base_url;

  $link_text = t("Size information");
  $language = \Drupal::languageManager()->getCurrentLanguage()->getId();

  switch ($type) {
    case 'vzutta':
      $markup = '<a class="use-ajax size-information" id="size-information" href="'. $base_url .'/'
        . $language . '/ajax/shoes-size-information/">' . $link_text . '</a>';
      break;
    case 'default':
      $markup = '<a class="use-ajax size-information" id="size-information" href="'. $base_url .'/'
        . $language . '/ajax/size-information/">' . $link_text . '</a>';
      break;
    default:
      $markup = '';
  }
  return $markup;
}

/**
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @return \Drupal\Core\Ajax\AjaxResponse
 */
function comment_ajax_callback(array &$form, FormStateInterface $form_state)
{
  $response = new AjaxResponse();
  if (!$form_state->hasAnyErrors()) {
    $options = array(
      'dialogClass' => 'popup-dialog-class',
      'width' => '300',
      'height' => '320',
    );
    $title = t('Subscribe to news');
    $email = $form_state->getValue('field_e_mail')[0]['value'];
    $content = _get_popup_content($email);
    $response->addCommand(new OpenModalDialogCommand($title, $content, $options));
  } else {
    $response->addCommand(new Ajax\ReplaceCommand('#comment-form', $form));
    $messages = drupal_get_messages(); // catch all messages
  }

  return $response;
}

/**
 * @param $email
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup|string
 */
function _get_popup_content($email)
{
  global $base_url;

  $succes_link = '<a class="ysub" href="'.$base_url.'/dadi/submit/subscribe/' . $email . '">' . t('Subscribe') . '</a>';
  $content = t('Would you like to subscribe to new items?');
  $content .= "<div class='popup-email'>" . $email . "</div>";
  $content .= '<div class="after-message">' . t('Any spam. Only useful information') . '</div>';
  $content .= '<div class="answer"><a href="/dadi/reset/subscribe">' . t('Don\'t subscribe') . '</a>';
  $content .= "$succes_link</div>";
  return $content;
}


/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function dadi_on_product_save_validation(&$form, FormStateInterface $form_state)
{
  $items_to_display = FALSE;

  if ($form_state->hasValue('variations')) {
    $variations = $form_state->getValue('variations');
    foreach ($variations['entities'] as $key => $value) {
      $comlete_form = $form_state->getCompleteForm();
      $entity = $comlete_form['variations']['widget']['entities'][$key];
      if ($entity) {
        $display_on_catalog = $entity['#entity']->get('field_on_catalog')
          ->getValue();
        if ($display_on_catalog[0]['value']) {
          $items_to_display = TRUE;
          break;
        }
      }
    }
    if (!$items_to_display) {
      $form_state->setErrorByName('variations', t('As min one variation must be displayed on catalog'));
    }
  }
}



/**
 * Implements hook_entity_extra_field_info().
 */
function dadi_entity_extra_field_info()
{
  $extra = array();
  foreach (ProductVariationType::loadMultiple() as $bundle) {
    $extra['commerce_product_variation'][$bundle->Id()]['display']['wish_button'] = array(
      'label' => t('Wishlist button'),
      'description' => t('Add to wishlist button'),
      'weight' => 100,
      'visible' => TRUE,
    );
  }

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function dadi_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode)
{
  if ($display->getComponent('wish_button')) {
    $id = $entity->get('variation_id')->getString();
    $link_text = t("Add to wishlist");
    global $base_path;
    $build['wish_button'] = [
      '#type' => 'markup',
      '#attached' => array(
        'library' => array(
          'dadi/wish-button',
        ),
      ),
      '#markup' => '<a class="use-ajax wishlist-button" id="variation-' . $id . '"
      href="' . $base_path . '/ajax/addtowishlist/' . $id . '"> ' . $link_text . '</a>',
    ];
  }
}

/**
 * Implements hook_preprocess_page().
 */
function dadi_preprocess_page(&$variables)
{
  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if (!$logged_in) {
    # Add libraries for anonymous
    $libraries['#attached']['library'][] = 'core/drupal.ajax';
    render($libraries);
  }
}

/**
 * Implements hook_theme().
 */
function dadi_theme($existing, $type, $theme, $path)
{
  return [
    'category_menu' => [
      'variables' => [
        'menu_tree' => [],
        'route_tid' => NULL,
        'vocabularies' => NULL,
        'current_depth' => 0,
        'max_depth' => 0,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dadi_preprocess_input(&$variables) {


  if (array_key_exists('#id', $variables['element'])) {
    $key = 'payment_information[billing_information][address][0][address]';
    $addressArray = [
      'given_name' => 'First Name',
      'family_name' => 'Last Name',
      'organization' => 'Company',
      'middle-name' => 'Middle name',
      'address_line1' => 'Address',
      'address_line2' => 'Secondary Address',
      'postal_code' =>'Posta Code',
      'locality' => 'City'
    ];
    $id = $variables['element']['#name'];
    foreach ($addressArray as $k => $name){
      $idSearch = $key.'['.$k.']';
      if($id == $idSearch){
        $variables['attributes']['placeholder']= $variables['element']['#title'];
      }
    }
  }
}
//payment_information[billing_information][address][0][address][given_name]
