<?php

/**
 * @file
 * Contains dadi.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dadi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dadi module.
    case 'help.page.dadi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dadi custom module') . '</p>';
      return $output;

    default:
  }
}
